version: 2.1

orbs:
  github-cli: &github_cli_version circleci/github-cli@1.0
  lumigo-orb: &lumigo_orb_version lumigo/lumigo-orb@volatile

executors:
  default:
    docker:
    - image: cimg/go:1.17

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

workflows:
  ci-build:
    jobs:
    - lumigo-orb/print_orb_versions:
        github_cli_version: *github_cli_version
        lumigo_orb_version: *lumigo_orb_version
    - test:
        context: common
        filters:
          branches:
            ignore: master

    - lumigo-orb/is_environment_available:
        context: common
        filters:
          branches:
            ignore: master

    - lumigo-orb/be-deploy:
        context: common
        requires:
          - lumigo-orb/is_environment_available

    - lumigo-orb/integration-test-prep:
        context: common
        run_test_cleanup: false
        requires:
          - lumigo-orb/be-deploy

    - lumigo-orb/integration-test-cleanup:
        name: pre-test-cleanup
        context: common
        requires:
          - lumigo-orb/integration-test-prep

    - lumigo-orb/integration-test-limited-flows:
        context: common
        run_test_cleanup: false
        requires:
          - pre-test-cleanup

    - lumigo-orb/integration-test-parallel:
        context: common
        run_test_cleanup: false
        requires:
          - lumigo-orb/integration-test-limited-flows

    - lumigo-orb/integration-test-cleanup:
        name: post-test-cleanup
        context: common
        requires:
          - lumigo-orb/integration-test-parallel

    - lumigo-orb/workflow-completed-successfully:
        context: common
        requires:
          - test
          - lumigo-orb/integration-test-parallel

  master-build:
    jobs:
    - test:
        context: common
        filters:
          branches:
            only:
            - master
    - create-push-release:
        context:
          - common
          - golang
        requires:
          - test

jobs:
  test:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: make checks
    - run: make upload-codecov
    - *save_cache

  create-push-release:
    executor:
      name: default
    steps:
    - github-cli/setup
    - checkout
    - run: |
        make release
