version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.17

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
  check-style:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: make check-style
    - *save_cache

  unit-tests:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: make test
    - *save_cache

workflows:
  version: 2
  
  ci-build:
    jobs:
    - check-style
    - unit-tests

  master-build:
    jobs:
    - check-style:
        filters:
          branches:
            only:
            - master
    - unit-tests:
        filters:
          branches:
            only:
            - master