version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.17

orbs:
  gh: circleci/github-cli@1.0

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
  checks:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: make checks
    - *save_cache
  
  create-push-release:
    executor:
      name: default
    steps:
      - run: |
          git log --oneline > changelog.md
          gh release create v1.0 -F changelog.md

workflows:
  version: 2
  
  ci-build:
    jobs:
    - checks

  master-build:
    jobs:
    - checks:
        filters:
          branches:
            only:
            - master

  release:
    jobs:
    - create-push-release